/* AI Audit Checklist v5 — static data (loaded before app.js) */

const STATUS = ['未接入', '偶尔', '常态', '高ROI'];
const HUMAN_STATUS = ['未标注', '已标注', '流程到位', 'AI仅辅助'];
const STATUS_MUL = [0, 0.5, 1, 1.2];

const ROLE_CATS = {
  all: null,
  office: ['life','office','complex','transform','human','industry','chat','workflow','creative','hardware'],
  dev: ['life','dev','complex','transform','human','industry','agents','chat','workflow','hardware'],
  biz: ['life','office','biz','complex','transform','human','industry','chat','workflow','creative'],
};

const DEFAULT_TOOL_PRICES = {
  A1: 145, A2: 145, A3: 145, A4: 100, A5: 100, A6: 0, A7: 0, A8: 0, A9: 100, A10: 100,
  A11: 0, A12: 145, A13: 0, A14: 145, A15: 145, A16: 145, A17: 0,
  T1: 145, T2: 145, T3: 100, T4: 30, T5: 0, T6: 0, T7: 0, T8: 0, T9: 140, T10: 0, T11: 100, T12: 0,
  F1: 0, F2: 0, F3: 140, F4: 200, F5: 0, F6: 60, F7: 80, F8: 0,
  M1: 80, M2: 80, M3: 200, M4: 80, M5: 120, M6: 60,
  H1: 0, H2: 0, H3: 0, H4: 0, H5: 0, H6: 0, H7: 0, H8: 0, H9: 0, H10: 0,
};

const PROMPT_LINKS = {
  W1: 'prompts/meeting-minutes.md',
  W2: 'prompts/weekly-report.md',
  W3: 'prompts/requirements-clarification.md',
  L2: 'prompts/execution-brief.md',
  D1: 'prompts/execution-brief.md',
  D4: 'engineering/code-review-prompt.md',
};

const CATEGORIES = [
  {
    id: 'life',
    name: '生活',
    icon: '🏠',
    items: [
      { id:'L1', title:'信息 intake · 摘要 → 值不值得读', problem:'信息过载、收藏吃灰', tools:'ChatGPT/Claude/Kimi/NotebookLM', base:45, now:12, freq:5 },
      { id:'L2', title:'写作沟通 · AI 起草 → 你改定稿', problem:'回复慢、表达拖延', tools:'Claude/ChatGPT/通义', base:40, now:12, freq:4 },
      { id:'L3', title:'学习 · 提纲/答疑/自测', problem:'长文啃不动、无人问', tools:'ChatGPT/Claude/Kimi', base:60, now:25, freq:3 },
      { id:'L4', title:'日/周复盘 · 归纳模式+行动项', problem:'忙无归纳、重复踩坑', tools:'对话AI+Notion/Obsidian', base:30, now:8, freq:2 },
      { id:'L5', title:'决策辅助 · 列选项利弊（你选）', problem:'选择瘫痪', tools:'Claude/ChatGPT', base:60, now:25, freq:1 },
      { id:'L6', title:'购物消费 · 比参数/评价摘要', problem:'研究商品费时', tools:'ChatGPT/Perplexity/豆包', base:120, now:25, freq:0.5 },
      { id:'L7', title:'健康 · 饮食运动计划（非诊断）', problem:'计划难坚持', tools:'ChatGPT/Apple Health', base:45, now:15, freq:1 },
      { id:'L8', title:'财务 · 账单分类/预算问答', problem:'账目乱', tools:'ChatGPT/Excel Copilot', base:60, now:20, freq:0.5 },
      { id:'L9', title:'出行/办事 · 行程/材料清单', problem:'查攻略慢', tools:'ChatGPT/Kimi/高德AI', base:90, now:20, freq:0.5 },
      { id:'L10', title:'灵感 capture · 语音→整理入库', problem:'想法丢失', tools:'Plaud/讯飞+AI/Apple快捷指令', base:20, now:5, freq:7 },
      { id:'L11', title:'家务/生活技巧 · 维修/烹饪/育儿问答', problem:'临时查教程', tools:'豆包/ChatGPT/小红书AI', base:30, now:8, freq:2 },
      { id:'L12', title:'人际关系 · 难处沟通草稿', problem:'不知怎么开口', tools:'Claude/ChatGPT', base:45, now:15, freq:0.5 },
      { id:'L16', title:'简历/面试模拟 · 整包准备', problem:'求职准备数天', tools:'Claude/ChatGPT', base:360, now:90, freq:0.05 },
      { id:'L17', title:'保险/理财方案比较（你决策）', problem:'产品复杂比不了', tools:'ChatGPT/Claude', base:180, now:45, freq:0.05 },
      { id:'L13', title:'语言学习 · 对话陪练/纠错', problem:'缺语伴', tools:'ChatGPT/多邻国Max', base:45, now:20, freq:3 },
      { id:'L14', title:'个人知识库 · RAG 检索自己的笔记', problem:'笔记找不到', tools:'NotebookLM/Obsidian Copilot', base:30, now:5, freq:4 },
      { id:'L15', title:'照片/记忆 · 相册搜索/旅行回顾', problem:'照片难找', tools:'Apple Intelligence/Google Photos AI', base:20, now:5, freq:1 },
    ]
  },
  {
    id: 'office',
    name: '办公协作',
    icon: '💼',
    items: [
      { id:'W1', title:'会议纪要 → action 表', problem:'会后整理慢、漏 action', tools:'ChatGPT/Claude/飞书妙记+AI', base:60, now:12, freq:3, prompt:'W1' },
      { id:'W2', title:'周报/方案 · 你 bullet → AI 初稿', problem:'写文档痛苦', tools:'Claude/ChatGPT/Notion AI', base:120, now:25, freq:1, prompt:'W2' },
      { id:'W3', title:'需求澄清 → PRD 骨架', problem:'需求扯皮', tools:'Claude/ChatGPT', base:90, now:30, freq:1, prompt:'W3' },
      { id:'W4', title:'数据分析 · 自然语言问数', problem:'不会 SQL/公式', tools:'ChatGPT/Excel Copilot/Julius', base:30, now:5, freq:4 },
      { id:'W5', title:'翻译润色 · 中英互译', problem:'对外文案慢', tools:'DeepL/Claude/ChatGPT', base:45, now:12, freq:2 },
      { id:'W6', title:'竞品/行业快研', problem:'调研散慢', tools:'Perplexity/ChatGPT/Kimi', base:240, now:60, freq:0.5 },
      { id:'W7', title:'PPT/汇报 · 大纲+演讲备注', problem:'搭结构难', tools:'Gamma/ChatGPT/Beautiful.ai', base:90, now:25, freq:0.5 },
      { id:'W8', title:'邮件/Message 批量回复', problem:'重复回复', tools:'ChatGPT/Superhuman AI', base:15, now:3, freq:5 },
      { id:'W9', title:'日历/会议 · 智能排期摘要', problem:'协调时间烦', tools:'Reclaim/Clockwise/飞书', base:30, now:8, freq:2 },
      { id:'W10', title:'合同/长文摘要（你终审）', problem:'读不完', tools:'Claude/ChatGPT', base:60, now:12, freq:1 },
      { id:'W11', title:'Excel/表格 · 公式生成/清洗', problem:'表格卡住', tools:'Excel Copilot/ChatGPT Code', base:45, now:10, freq:3 },
      { id:'W12', title:'面试/招聘 · JD/问题清单', problem:'写 JD 慢', tools:'ChatGPT/Claude', base:60, now:15, freq:0.3 },
      { id:'W13', title:'跨部门项目 Sync 材料整合', problem:'多方信息拼慢', tools:'Claude/ChatGPT', base:180, now:45, freq:0.3 },
      { id:'W14', title:'SOP/流程文档整库生成', problem:'流程文档缺失', tools:'Claude/Notion AI', base:480, now:120, freq:0.05 },
      { id:'W15', title:'预算/预测模型说明+叙事', problem:'财务沟通难', tools:'ChatGPT+Excel', base:240, now:60, freq:0.1 },
    ]
  },
  {
    id: 'dev',
    name: '研发工程',
    icon: '⚙️',
    items: [
      { id:'D1', title:'编码实现 · 你定标准 → Agent 写', problem:'样板代码慢', tools:'Cursor Agent/Claude Code/Copilot', base:2400, now:1440, freq:0.25 },
      { id:'D2', title:'重构/ tech debt', problem:'不敢 refactor', tools:'Cursor/Claude Code', base:480, now:240, freq:0.2 },
      { id:'D3', title:'单元/集成测试生成', problem:'覆盖不足', tools:'Cursor/Copilot/Codex', base:120, now:30, freq:1 },
      { id:'D4', title:'Code Review 初筛', problem:'review 瓶颈', tools:'Cursor/Claude/Coderabbit', base:30, now:8, freq:5, prompt:'D4' },
      { id:'D5', title:'文档/API 同步生成', problem:'文档过时', tools:'Cursor/Swag AI', base:60, now:15, freq:0.5 },
      { id:'D6', title:'排障 · 日志→假设→patch', problem:'日志海', tools:'Cursor/ChatGPT/Claude', base:90, now:25, freq:1 },
      { id:'D7', title:'CI/构建失败解读', problem:'看不懂红字', tools:'Cursor/Copilot', base:45, now:10, freq:1 },
      { id:'D8', title:'依赖/安全升级分析', problem:'不敢升', tools:'Dependabot+AI/Cursor', base:60, now:15, freq:0.3 },
      { id:'D9', title:'架构设计 · 方案对比（你选）', problem:'方案想不全', tools:'Claude/ChatGPT/o1', base:120, now:40, freq:0.3 },
      { id:'D10', title:'SQL/正则/脚本一次性生成', problem:'语法记不住', tools:'Cursor/Codex/ChatGPT', base:30, now:5, freq:3 },
      { id:'D11', title:'Migration/数据脚本', problem:'迁移怕出错', tools:'Claude Code/Cursor', base:120, now:40, freq:0.2 },
      { id:'D12', title:'Terminal/运维命令辅助', problem:'命令记不住', tools:'Warp AI/Fig/Cursor', base:20, now:5, freq:2 },
      { id:'D13', title:'陌生 SDK/API 整集成', problem:'读文档集成慢', tools:'Cursor/CC/Codex', base:480, now:120, freq:0.1 },
      { id:'D14', title:'App Store/上架材料+审核回复', problem:'上架琐事', tools:'ChatGPT/Cursor', base:240, now:60, freq:0.05 },
      { id:'D15', title:'数据管道 ETL 脚本生成', problem:'管道搭建慢', tools:'Claude Code/Cursor', base:360, now:90, freq:0.08 },
    ]
  },
  {
    id: 'biz',
    name: '业务产品',
    icon: '📈',
    items: [
      { id:'B1', title:'内部知识问答 RAG', problem:'重复答 HR/IT', tools:'Dify/Coze/飞书知识库', base:8, now:2, freq:10 },
      { id:'B2', title:'对外客服 FAQ + 转人工', problem:'客服压力', tools:'Dify/Intercom AI/Zendesk AI', base:8, now:2, freq:20 },
      { id:'B3', title:'销售话术/提案/投标', problem:'提案慢', tools:'ChatGPT/Claude/Jasper', base:180, now:45, freq:0.5 },
      { id:'B4', title:'工单自动分类路由', problem:'人工分单', tools:'Zapier AI/n8n/自研', base:5, now:1, freq:20 },
      { id:'B5', title:'审批/合同摘要', problem:'长文读不完', tools:'Claude/ChatGPT', base:30, now:8, freq:3 },
      { id:'B6', title:'产品内 AI 功能', problem:'竞品压力', tools:'OpenAI API/自研 Agent', base:0, now:0, freq:0 },
      { id:'B7', title:'营销文案/SEO/投放素材', problem:'产出慢', tools:'ChatGPT/Midjourney/Jasper', base:120, now:30, freq:1 },
      { id:'B8', title:'用户反馈/评论情感分析', problem:'看不完反馈', tools:'ChatGPT/MonkeyLearn', base:60, now:10, freq:0.5 },
      { id:'B9', title:'用户访谈 → 洞察报告（重度）', problem:'访谈整理数天', tools:'Claude/ChatGPT/Dovetail AI', base:480, now:120, freq:0.15, mode:'direct' },
      { id:'B10', title:'季度 OKR/路线图制定', problem:'对齐耗时长', tools:'Claude/ChatGPT/Notion AI', base:360, now:90, freq:0.08, mode:'direct' },
      { id:'B11', title:'定价/商业化策略分析', problem:'决策信息散', tools:'Claude/o1/Perplexity', base:480, now:120, freq:0.08, mode:'direct' },
      { id:'B12', title:'流失/留存分析与挽回方案', problem:'数据分析+策略慢', tools:'ChatGPT+BI/Julius', base:360, now:90, freq:0.15, mode:'direct' },
    ]
  },
  {
    id: 'complex',
    name: '复杂长任务',
    icon: '🔥',
    desc: '单次 2h+ · AI 可直接重度辅助（你决策终审）',
    items: [
      { id:'X1', title:'读懂 legacy 代码库 / 新人 onboarding', problem:'接手老项目数天懵', tools:'Cursor/CC + codebase chat', base:2400, now:480, freq:0.05, mode:'direct' },
      { id:'X2', title:'深度行业/赛道研究报告', problem:'调研 1–3 天', tools:'Perplexity Deep/o1/Claude', base:960, now:180, freq:0.1, mode:'direct' },
      { id:'X3', title:'完整简历+作品集+求职策略 overhaul', problem:'跳槽准备数天', tools:'Claude/ChatGPT', base:480, now:120, freq:0.05, mode:'direct' },
      { id:'X4', title:'年度财务梳理 / 报税材料整理', problem:'账目整里一整天', tools:'ChatGPT+Excel/CPA 终审', base:480, now:120, freq:0.02, mode:'direct' },
      { id:'X5', title:'跨月项目计划+WBS+风险登记', problem:'大项目规划半天+', tools:'Claude/ChatGPT/Notion AI', base:360, now:90, freq:0.15, mode:'direct' },
      { id:'X6', title:'融资/董事会/投资人 Deck', problem:'材料准备 1–2 天', tools:'Claude/Gamma/ChatGPT', base:720, now:180, freq:0.05, mode:'direct' },
      { id:'X7', title:'合规/监管长文审查摘要', problem:'法务文本读不完', tools:'Claude 200K/ChatGPT', base:360, now:90, freq:0.1, mode:'direct' },
      { id:'X8', title:'多源用户研究综合 → 洞察报告', problem:'访谈+问卷整理数天', tools:'Claude/Dovetail/ChatGPT', base:960, now:240, freq:0.1, mode:'direct' },
      { id:'X9', title:'完整培训课程/手册体系搭建', problem:'做课一周+', tools:'ChatGPT/NotebookLM', base:2400, now:600, freq:0.03, mode:'direct' },
      { id:'X10', title:'事故 Postmortem + 改进跟踪', problem:'复盘写报告慢', tools:'Claude/ChatGPT', base:180, now:45, freq:0.2, mode:'direct' },
      { id:'X11', title:'Agent 自治多文件功能（数小时–数天）', problem:'跨模块开发周期长', tools:'Cursor Agent/CC/Devin', base:2400, now:960, freq:0.1, mode:'direct' },
      { id:'X12', title:'整模块 E2E/回归测试套件生成', problem:'补测试数天', tools:'Cursor/Copilot/Codex', base:960, now:240, freq:0.05, mode:'direct' },
      { id:'X13', title:'安全审计/漏洞报告初筛+修复计划', problem:'安全评估数天', tools:'Cursor+Snyk+AI', base:480, now:120, freq:0.05, mode:'direct' },
      { id:'X14', title:'全库 Migration / 数据迁移方案+脚本', problem:'迁移方案+执行慢', tools:'Claude Code/Cursor', base:960, now:360, freq:0.03, mode:'direct' },
      { id:'X15', title:'季度产品路线图+版本规划', problem:'规划对齐一整天', tools:'Claude/ChatGPT', base:480, now:120, freq:0.08, mode:'direct' },
      { id:'X16', title:'GTM / 产品上市方案全套', problem:'上市策划数天', tools:'Claude/ChatGPT/Jasper', base:720, now:180, freq:0.05, mode:'direct' },
      { id:'X17', title:'合同/协议初稿起草（律师终审）', problem:'合同从零写慢', tools:'Claude/ChatGPT', base:360, now:90, freq:0.1, mode:'direct' },
      { id:'X18', title:'招标 RFP 撰写+供应商评估矩阵', problem:'采购流程数天', tools:'Claude/ChatGPT', base:600, now:150, freq:0.05, mode:'direct' },
      { id:'X19', title:'360 绩效评估/晋升材料撰写', problem:'评估季痛苦', tools:'Claude/ChatGPT', base:240, now:60, freq:0.15, mode:'direct' },
      { id:'X20', title:'大型生活规划（搬家/婚礼/装修/留学）', problem:'复杂事务统筹数天', tools:'ChatGPT/Claude/Kimi', base:720, now:180, freq:0.03, mode:'direct' },
      { id:'X21', title:'竞品功能矩阵+差异化策略（深度）', problem:'竞品分析 1 天+', tools:'Perplexity/Claude/ChatGPT', base:480, now:120, freq:0.15, mode:'direct' },
      { id:'X22', title:'整仓文档生成/更新（与代码同步）', problem:'文档债累积', tools:'Cursor/Swag AI', base:960, now:240, freq:0.05, mode:'direct' },
      { id:'X23', title:'性能 profiling 报告+优化方案', problem:'性能排查数小时–天', tools:'Cursor/ChatGPT+APM', base:480, now:120, freq:0.08, mode:'direct' },
      { id:'X24', title:'微服务拆分/架构演进方案', problem:'架构设计数天', tools:'Claude/o1/CC', base:720, now:180, freq:0.05, mode:'direct' },
      { id:'X25', title:'Medical/体检报告整理+提问清单（非诊断）', problem:'报告看不懂', tools:'ChatGPT/Claude', base:120, now:30, freq:0.1, mode:'direct' },
    ]
  },
  {
    id: 'transform',
    name: '流程改造',
    icon: '🔄',
    desc: '原流程耗时长 → 改造成 AI 流水线后可覆盖',
    items: [
      { id:'R1', title:'人工调研 → Deep Research + 你核实', problem:'调研从 2 天压到 2h', tools:'Perplexity/o1/Claude', base:960, now:120, freq:0.1, mode:'transform' },
      { id:'R2', title:'手工录数据 → OCR/截图 + AI 提取 + 你确认', problem:'录入几小时', tools:'GPT-4V/通义/飞书 OCR', base:240, now:30, freq:0.3, mode:'transform' },
      { id:'R3', title:'纯人工客服 → RAG 问答 + 人工兜底', problem:'重复答 80% 问题', tools:'Dify/Coze/Intercom', base:480, now:60, freq:1, mode:'transform' },
      { id:'R4', title:'手工 QA → AI 探索测试 + 人 sign-off', problem:'回归测不完', tools:'Cursor/Mobile AI/Playwright+AI', base:480, now:120, freq:0.2, mode:'transform' },
      { id:'R5', title:'口头 onboarding → AI 引导 + 知识库', problem:'新人问同样问题', tools:'RAG+Notion/飞书', base:480, now:60, freq:0.3, mode:'transform' },
      { id:'R6', title:'手工周报 → 数据拉取 + AI 叙事', problem:'每周凑数据 2h', tools:'n8n+ChatGPT/BI Copilot', base:120, now:25, freq:1, mode:'transform' },
      { id:'R7', title:'人工排障 → 日志聚合 + AI 假设排序', problem:'MTTR 长', tools:'Datadog+AI/Cursor', base:180, now:40, freq:0.5, mode:'transform' },
      { id:'R8', title:'手工纪要 → 录音自动流水线总结', problem:'会后必痛苦', tools:'飞书妙记/Plaud+AI', base:60, now:10, freq:3, mode:'transform' },
      { id:'R9', title:'可选 Code Review → AI 全 PR 强制初筛', problem:'review 排队', tools:'Coderabbit/Cursor/Claude', base:60, now:12, freq:5, mode:'transform' },
      { id:'R10', title:'补测试 → Spec 驱动 AI 生成 + CI 卡点', problem:'测试债', tools:'Cursor/Copilot', base:480, now:90, freq:0.15, mode:'transform' },
      { id:'R11', title:'手工竞品监控 → 定时 Agent 抓取+推送', problem:'信息滞后', tools:'n8n/Coze/Perplexity API', base:240, now:30, freq:0.5, mode:'transform' },
      { id:'R12', title:'手工 i18n → 提取+AI 翻译+人审', problem:'本地化数周', tools:'Lokalise+AI/Cursor', base:960, now:240, freq:0.05, mode:'transform' },
      { id:'R13', title:'Excel 手工 → NL 问数 + 固定模板自动化', problem:'表格劳动', tools:'Excel Copilot/Python+AI', base:180, now:30, freq:1, mode:'transform' },
      { id:'R14', title:'审批读全文 → 摘要+风险标记+你批', problem:'审批堆积', tools:'Claude/ChatGPT', base:45, now:8, freq:5, mode:'transform' },
      { id:'R15', title:'人工筛简历 → AI 结构化匹配+你面', problem:'HR 初筛慢', tools:'ChatGPT/ATS AI', base:360, now:60, freq:0.2, mode:'transform' },
      { id:'R16', title:'临时想内容 → 内容日历 AI 生成+你发', problem:'运营断更', tools:'ChatGPT/Coze', base:240, now:45, freq:0.5, mode:'transform' },
      { id:'R17', title:' ad-hoc 分析 → Text-to-SQL + 固定看板', problem:'每次重新取数', tools:'Julius/Metabase AI', base:120, now:15, freq:2, mode:'transform' },
      { id:'R18', title:'手工部署 → Agent 脚本+你 approve', problem:'部署步骤多', tools:'Claude Code/Cursor/CI', base:120, now:25, freq:0.3, mode:'transform' },
      { id:'R19', title:'文档腐烂 → 代码变更触发 AI 文档 sync', problem:'文档永远旧', tools:'Cursor/Swag/hooks', base:480, now:60, freq:0.1, mode:'transform' },
      { id:'R20', title:'啃新课 → 资料丢 NotebookLM + 复习计划', problem:'学习无体系', tools:'NotebookLM/ChatGPT', base:600, now:120, freq:0.15, mode:'transform' },
      { id:'R21', title:'人工社媒回复 → AI 草稿 inbox + 你批', problem:'评论回不过来', tools:'Coze/ChatGPT', base:120, now:20, freq:1, mode:'transform' },
      { id:'R22', title:'会议串讲 → 多会议合并 digest + 决策项', problem:'会太多', tools:'AI+日历/飞书', base:90, now:20, freq:2, mode:'transform' },
      { id:'R23', title:'Browser 重复操作 → Computer Use Agent', problem:'网页点重复', tools:'Operator/Claude CU/Manus', base:180, now:30, freq:0.5, mode:'transform' },
      { id:'R24', title:'Spec 驱动开发 → PRD→Task→Agent 循环', problem:'需求到代码链路长', tools:'Cursor/CC+TaskMaster', base:2400, now:720, freq:0.1, mode:'transform' },
      { id:'R25', title:'个人 inbox 清零 → 邮件/消息 AI 分类+草稿', problem:'消息堆积', tools:'Superhuman/Shortwave AI', base:60, now:10, freq:5, mode:'transform' },
    ]
  },
  {
    id: 'human',
    name: '人工必须',
    icon: '🛡️',
    desc: '不能/不应全交 AI · 你决策终审 · 勾选=边界已建立',
    items: [
      { id:'N1', title:'最终商业 / 战略 / 人生重大决策', problem:'AI 不承担后果', tools:'AI仅可列选项+利弊', humanOnly:true, aiRole:'列选项备料，你拍板', timeW: 5.4 },
      { id:'N2', title:'对外法律签约 / 法务意见定稿', problem:'法律责任在人', tools:'AI仅可摘要风险', humanOnly:true, aiRole:'摘要+问题清单，律师/你签', timeW: 5.4 },
      { id:'N3', title:'财务定稿 / 审计 sign-off / 报税签字', problem:'合规与数字准确性', tools:'AI仅可整理分类', humanOnly:true, aiRole:'整理账目，你/CPA 确认', timeW: 5.4 },
      { id:'N4', title:'医疗诊断 / 用药 / 治疗方案决定', problem:'监管与安全', tools:'AI不可替代医生', humanOnly:true, aiRole:'整理报告+提问清单', timeW: 5.4 },
      { id:'N5', title:'人事解雇 / 纪律 / 敏感 HR 决定', problem:'人道+法律', tools:'AI仅可起草框架', humanOnly:true, aiRole:'流程 checklist，你/HR 面谈', timeW: 5.4 },
      { id:'N6', title:'危机公关 / 舆情最终对外口径', problem:'声誉不可逆', tools:'AI仅可草稿', humanOnly:true, aiRole:'多版草稿，你定稿发布', timeW: 5.4 },
      { id:'N7', title:'亲密关系 / 信任 / 情感修复', problem:'需要真人在场', tools:'AI仅可措辞建议', humanOnly:true, aiRole:'草稿参考，必须真人沟通', timeW: 5.4 },
      { id:'N8', title:'育儿 / 教育价值观与关键谈话', problem:'家长角色不可替代', tools:'AI仅可备料', humanOnly:true, aiRole:'资料+话术参考，你来讲', timeW: 5.4 },
      { id:'N9', title:'艺术创作最终审美 / 品牌调性定稿', problem:'个人/品牌表达', tools:'AI仅可出草案', humanOnly:true, aiRole:'多版本，你选方向', timeW: 5.4 },
      { id:'N10', title:'考试现场 / 认证作弊式代写', problem:'诚信与规则', tools:'禁止 AI 代做', humanOnly:true, aiRole:'仅可平时学习辅助', timeW: 5.4 },
      { id:'N11', title:'物理施工 / 手术 / 危险现场操作', problem:'人身安全', tools:'AI不可操作物理世界', humanOnly:true, aiRole:'可查规范，人动手', timeW: 5.4 },
      { id:'N12', title:'敏感数据未脱敏输入 AI', problem:'泄露合规风险', tools:'禁止', humanOnly:true, aiRole:'先脱敏或企业版', timeW: 5.4 },
      { id:'N13', title:'支付 / 鉴权 / 安全关键代码最终 merge', problem:'幻觉=事故', tools:'AI Review+人终审', humanOnly:true, aiRole:'AI 初筛，你 merge', timeW: 5.4 },
      { id:'N14', title:'道德 / 伦理 / 价值观最终判断', problem:'AI 无价值立场', tools:'AI仅可列框架', humanOnly:true, aiRole:'伦理矩阵，你判断', timeW: 5.4 },
      { id:'N15', title:'谈判最终让步 / 底价 / 成交拍板', problem:'关系+策略', tools:'AI仅可模拟', humanOnly:true, aiRole:'角色扮演备练，你上桌', timeW: 5.4 },
      { id:'N16', title:'投资 / 大额资金最终下单', problem:'盈亏责任在个人', tools:'AI仅可研究', humanOnly:true, aiRole:'研报摘要，你决策', timeW: 5.4 },
      { id:'N17', title:'隐私政策 / 用户 Consent 法律承诺', problem:'法律责任', tools:'AI仅可起草', humanOnly:true, aiRole:'法务+你终审', timeW: 5.4 },
      { id:'N18', title:'安全事件是否对外披露 / 披露内容', problem:'合规+声誉', tools:'AI仅可 timeline', humanOnly:true, aiRole:'事实整理，你决策', timeW: 5.4 },
      { id:'N19', title:'团队信任 / 士气 / 关键 1on1', problem:'管理需人性化', tools:'AI仅可谈话提纲', humanOnly:true, aiRole:'提纲参考，真人面谈', timeW: 5.4 },
      { id:'N20', title:'合同当面签署 / 见证 / 物理交付', problem:'物理+法律', tools:'不可远程 AI 代签', humanOnly:true, aiRole:'电子档 AI 辅助，签靠人', timeW: 5.4 },
      { id:'N21', title:'绩效最终评级 / 晋升否决权', problem:'影响他人生涯', tools:'AI仅可整理证据', humanOnly:true, aiRole:'材料整理，经理决策', timeW: 5.4 },
      { id:'N22', title:'产品上线 / 停产最终 go-no-go', problem:'业务后果', tools:'AI仅可 checklist', humanOnly:true, aiRole:'风险清单，PM/你拍板', timeW: 5.4 },
      { id:'N23', title:'新闻采访 / 公开演讲即兴承诺', problem:'一句话收不回', tools:'AI仅可备稿', humanOnly:true, aiRole:'Q&A 备练，现场你负责', timeW: 5.4 },
      { id:'N24', title:'未成年人 / 特殊群体相关决策', problem:'保护与合规', tools:'限制 AI 使用', humanOnly:true, aiRole:'极谨慎，人多审', timeW: 5.4 },
      { id:'N25', title:'向监管 / 政府正式申报与回应', problem:'法律后果', tools:'AI仅可草稿', humanOnly:true, aiRole:'专业顾问+你提交', timeW: 5.4 },
    ]
  },
  {
    id: 'agents',
    name: '编程 Agent',
    icon: '🤖',
    items: [
      { id:'A1', title:'Cursor Agent · 多文件自主改码', problem:'跨文件任务慢', tools:'Cursor Pro/Business', base:0, now:0, freq:0, isTool:true },
      { id:'A2', title:'Claude Code (CC) · 终端编程 Agent', problem:'CLI 工作流', tools:'Claude Pro/Max', base:0, now:0, freq:0, isTool:true },
      { id:'A3', title:'OpenAI Codex / Codex CLI', problem:'云端沙箱执行', tools:'ChatGPT Pro/Codex', base:0, now:0, freq:0, isTool:true },
      { id:'A4', title:'GitHub Copilot · Agent/Coding Agent', problem:'GitHub 生态', tools:'Copilot Pro+', base:0, now:0, freq:0, isTool:true },
      { id:'A5', title:'Windsurf Cascade Agent', problem:'IDE 内 Agent', tools:'Windsurf Pro', base:0, now:0, freq:0, isTool:true },
      { id:'A6', title:'Cline / Roo Code · VS Code Agent', problem:'开源可配模型', tools:'VS Code+Cline', base:0, now:0, freq:0, isTool:true },
      { id:'A7', title:'Aider · Git 感知终端 pair', problem:'终端偏好', tools:'Aider+API', base:0, now:0, freq:0, isTool:true },
      { id:'A8', title:'Devin / 类似全自动工程师', problem:'长任务自治', tools:'Devin/Cognition', base:0, now:0, freq:0, isTool:true },
      { id:'A9', title:'Bolt.new / Lovable · 全栈生成', problem:'从 0 到 MVP', tools:'Bolt/Lovable', base:0, now:0, freq:0, isTool:true },
      { id:'A10', title:'Replit Agent · 云端构建部署', problem:'快速原型', tools:'Replit Core', base:0, now:0, freq:0, isTool:true },
      { id:'A11', title:'OpenHands / SWE-Agent 开源', problem:'自托管 Agent', tools:'Docker+GPU', base:0, now:0, freq:0, isTool:true },
      { id:'A12', title:'v0 · UI 组件生成', problem:'前端 UI 慢', tools:'Vercel v0', base:0, now:0, freq:0, isTool:true },
      { id:'A13', title:'Manus / 通用任务 Agent', problem:'长任务自治', tools:'Manus', base:0, now:0, freq:0, isTool:true },
      { id:'A14', title:'OpenAI Operator · Computer Use', problem:'浏览器自动化', tools:'ChatGPT Pro', base:0, now:0, freq:0, isTool:true },
      { id:'A15', title:'Claude Computer Use', problem:'GUI 操作 Agent', tools:'Claude', base:0, now:0, freq:0, isTool:true },
      { id:'A16', title:'Multi-hour Agent · 数小时级任务', problem:'跨步长任务', tools:'CC/Cursor/Devin', base:0, now:0, freq:0, isTool:true },
      { id:'A17', title:'TaskMaster / Spec→Task 分解', problem:'大需求拆任务', tools:'TaskMaster AI', base:0, now:0, freq:0, isTool:true },
    ]
  },
  {
    id: 'chat',
    name: '对话与助手',
    icon: '💬',
    items: [
      { id:'T1', title:'ChatGPT · GPT-4o/o1/Pro', problem:'通用对话+推理', tools:'OpenAI', base:0, now:0, freq:0, isTool:true },
      { id:'T2', title:'Claude · Sonnet/Opus', problem:'长文+写作+代码', tools:'Anthropic', base:0, now:0, freq:0, isTool:true },
      { id:'T3', title:'Gemini · Advanced/Workspace', problem:'Google 生态', tools:'Google', base:0, now:0, freq:0, isTool:true },
      { id:'T4', title:'DeepSeek · 推理/代码', problem:'性价比代码', tools:'DeepSeek', base:0, now:0, freq:0, isTool:true },
      { id:'T5', title:'Kimi · 长上下文', problem:'长文档', tools:'月之暗面', base:0, now:0, freq:0, isTool:true },
      { id:'T6', title:'通义千问 · 钉钉/阿里云', problem:'国内合规', tools:'阿里', base:0, now:0, freq:0, isTool:true },
      { id:'T7', title:'文心一言 · 百度生态', problem:'国内搜索', tools:'百度', base:0, now:0, freq:0, isTool:true },
      { id:'T8', title:'豆包 · 字节系', problem:'免费+移动端', tools:'字节', base:0, now:0, freq:0, isTool:true },
      { id:'T9', title:'Perplexity · 搜索+引用', problem:'要来源的调研', tools:'Perplexity', base:0, now:0, freq:0, isTool:true },
      { id:'T10', title:'NotebookLM · 文档播客/RAG', problem:'资料变可问', tools:'Google', base:0, now:0, freq:0, isTool:true },
      { id:'T11', title:'Grok · X/Twitter 集成', problem:'社交实时', tools:'xAI', base:0, now:0, freq:0, isTool:true },
      { id:'T12', title:'企业版 · 数据不训练', problem:'工作合规', tools:'Team/Enterprise', base:0, now:0, freq:0, isTool:true },
    ]
  },
  {
    id: 'workflow',
    name: '自动化平台',
    icon: '🔗',
    items: [
      { id:'F1', title:'Coze / 扣子 · Bot+插件', problem:'国内 Bot 快搭', tools:'字节 Coze', base:0, now:0, freq:0, isTool:true },
      { id:'F2', title:'Dify · RAG+Agent 开源', problem:'私有化 RAG', tools:'Dify', base:0, now:0, freq:0, isTool:true },
      { id:'F3', title:'n8n / Make · AI 工作流', problem:'跨 App 自动化', tools:'n8n/Make', base:0, now:0, freq:0, isTool:true },
      { id:'F4', title:'Zapier AI Actions', problem:'SaaS 连线', tools:'Zapier', base:0, now:0, freq:0, isTool:true },
      { id:'F5', title:'Apple 快捷指令 + AI', problem:'手机自动化', tools:'Shortcuts', base:0, now:0, freq:0, isTool:true },
      { id:'F6', title:'Raycast AI / Alfred AI', problem:'Mac 启动器 AI', tools:'Raycast', base:0, now:0, freq:0, isTool:true },
      { id:'F7', title:'Notion AI / 飞书智能', problem:'文档内 AI', tools:'Notion/飞书', base:0, now:0, freq:0, isTool:true },
      { id:'F8', title:'Obsidian Copilot 插件', problem:'本地笔记 RAG', tools:'Obsidian', base:0, now:0, freq:0, isTool:true },
    ]
  },
  {
    id: 'creative',
    name: '创意多媒体',
    icon: '🎨',
    items: [
      { id:'M1', title:'Midjourney / DALL·E / SD', problem:'出图', tools:'MJ/DALL-E', base:0, now:0, freq:0, isTool:true },
      { id:'M2', title:'Suno / Udio · AI 音乐', problem:'配乐', tools:'Suno', base:0, now:0, freq:0, isTool:true },
      { id:'M3', title:'Runway / Kling / Sora', problem:'视频生成', tools:'Runway/Kling', base:0, now:0, freq:0, isTool:true },
      { id:'M4', title:'ElevenLabs · 语音合成', problem:'配音', tools:'ElevenLabs', base:0, now:0, freq:0, isTool:true },
      { id:'M5', title:'Descript / 剪映 AI', problem:'剪辑', tools:'Descript/剪映', base:0, now:0, freq:0, isTool:true },
      { id:'M6', title:'Canva AI / 稿定 AI', problem:'设计模板', tools:'Canva', base:0, now:0, freq:0, isTool:true },
    ]
  },
  {
    id: 'hardware',
    name: 'AI 硬件',
    icon: '📱',
    items: [
      { id:'H1', title:'AI PC · NPU (Copilot+ PC)', problem:'本地推理/隐私', tools:'Intel/AMD/高通 X Elite', base:0, now:0, freq:0, isTool:true },
      { id:'H2', title:'Apple Silicon Mac · M系列', problem:'本地小模型+开发', tools:'MacBook/Mac mini', base:0, now:0, freq:0, isTool:true },
      { id:'H3', title:'本地 GPU 工作站 · Ollama', problem:'私有化大模型', tools:'NVIDIA RTX + Ollama', base:0, now:0, freq:0, isTool:true },
      { id:'H4', title:'Plaud Note / 录音卡片', problem:'会议/灵感录音→AI', tools:'Plaud', base:0, now:0, freq:0, isTool:true },
      { id:'H5', title:'Apple Intelligence · iPhone/Mac', problem:'系统级摘要/写作', tools:'iOS 18+/macOS', base:0, now:0, freq:0, isTool:true },
      { id:'H6', title:'智能眼镜 · Meta Ray-Ban 等', problem:'第一视角 capture', tools:'Meta/雷鸟', base:0, now:0, freq:0, isTool:true },
      { id:'H7', title:'AI 鼠标/键盘 · 快捷唤醒', problem:'物理一键 AI', tools:'Various', base:0, now:0, freq:0, isTool:true },
      { id:'H8', title:'智能音箱 · 语音助手', problem:'家居语音', tools:'小爱/天猫/ HomePod', base:0, now:0, freq:0, isTool:true },
      { id:'H9', title:'Apple Watch / 健康 AI 解读', problem:'健康数据理解', tools:'Apple Watch', base:0, now:0, freq:0, isTool:true },
      { id:'H10', title:'VR/AR · Vision Pro 空间计算', problem:'沉浸式协作', tools:'Vision Pro', base:0, now:0, freq:0, isTool:true },
    ]
  },
  {
    id: 'industry',
    name: '垂直行业',
    icon: '🏭',
    desc: '电商/教育/律所/医疗/制造/金融 · 行业场景映射',
    items: [
      { id:'I1', title:'电商 · 商品文案/详情/客服话术', problem:'SKU 多产出慢', tools:'ChatGPT/Jasper/店小秘 AI', base:45, now:12, freq:5 },
      { id:'I2', title:'教育 · 教案/习题/作业反馈', problem:'备课批改耗时', tools:'ChatGPT/Claude/讯飞', base:90, now:25, freq:3 },
      { id:'I3', title:'律所 · 案例检索/文书初稿（律师终审）', problem:'检索起草慢', tools:'Claude/ChatGPT/法律 AI', base:180, now:45, freq:1 },
      { id:'I4', title:'医疗文书 · 病历整理/出院小结（非诊断）', problem:'文书负担重', tools:'Claude/专科 AI · 人审', base:60, now:15, freq:4 },
      { id:'I5', title:'制造 · SOP/质检报告/设备维保记录', problem:'现场文档滞后', tools:'ChatGPT+MES/Notion AI', base:90, now:20, freq:2 },
      { id:'I6', title:'金融 · 合规摘要/研报/风险简报', problem:'信息密集读不完', tools:'Claude/ChatGPT/Bloomberg AI', base:120, now:30, freq:2 },
    ]
  },

];
