/* English item copy — loaded before app.js */
const ITEMS_EN = {
  L1: { title: 'Information intake · Summarize → worth reading?', problem: 'Information overload; saved items never read', tools: 'ChatGPT/Claude/Kimi/NotebookLM' },
  L2: { title: 'Writing & communication · AI drafts → you finalize', problem: 'Slow replies; procrastination on writing', tools: 'Claude/ChatGPT/通义' },
  L3: { title: 'Learning · Outlines / Q&A / self-quizzes', problem: 'Long articles hard to digest; no one to ask', tools: 'ChatGPT/Claude/Kimi' },
  L4: { title: 'Daily/weekly review · Pattern summary + action items', problem: 'Busy with no reflection; repeat same mistakes', tools: 'Chat AI + Notion/Obsidian' },
  L5: { title: 'Decision support · List options & trade-offs (you choose)', problem: 'Decision paralysis', tools: 'Claude/ChatGPT' },
  L6: { title: 'Shopping · Compare specs & review summaries', problem: 'Product research takes too long', tools: 'ChatGPT/Perplexity/豆包' },
  L7: { title: 'Health · Diet & exercise plans (not diagnosis)', problem: 'Hard to stick to a plan', tools: 'ChatGPT/Apple Health' },
  L8: { title: 'Finance · Bill categorization & budget Q&A', problem: 'Messy accounts', tools: 'ChatGPT/Excel Copilot' },
  L9: { title: 'Travel & errands · Itineraries & document checklists', problem: 'Slow to research plans', tools: 'ChatGPT/Kimi/高德AI' },
  L10: { title: 'Idea capture · Voice → organized archive', problem: 'Ideas get lost', tools: 'Plaud/讯飞+AI/Apple Shortcuts' },
  L11: { title: 'Household & life tips · Repair / cooking / parenting Q&A', problem: 'Ad-hoc tutorial lookups', tools: '豆包/ChatGPT/小红书AI' },
  L12: { title: 'Relationships · Draft difficult conversations', problem: 'Not sure how to start', tools: 'Claude/ChatGPT' },
  L13: { title: 'Language learning · Conversation practice & correction', problem: 'No speaking partner', tools: 'ChatGPT/Duolingo Max' },
  L14: { title: 'Personal knowledge base · RAG search over your notes', problem: 'Notes impossible to find', tools: 'NotebookLM/Obsidian Copilot' },
  L15: { title: 'Photos & memories · Album search & trip recaps', problem: 'Photos hard to locate', tools: 'Apple Intelligence/Google Photos AI' },
  L16: { title: 'Resume & interview prep · Full package', problem: 'Job search prep takes days', tools: 'Claude/ChatGPT' },
  L17: { title: 'Insurance & financial plan comparison (you decide)', problem: 'Products too complex to compare', tools: 'ChatGPT/Claude' },

  W1: { title: 'Meeting notes → action table', problem: 'Slow post-meeting cleanup; missed action items', tools: 'ChatGPT/Claude/飞书妙记+AI' },
  W2: { title: 'Weekly reports & proposals · Your bullets → AI first draft', problem: 'Painful document writing', tools: 'Claude/ChatGPT/Notion AI' },
  W3: { title: 'Requirements clarification → PRD skeleton', problem: 'Requirements disputes', tools: 'Claude/ChatGPT' },
  W4: { title: 'Data analysis · Natural language queries', problem: "Don't know SQL or formulas", tools: 'ChatGPT/Excel Copilot/Julius' },
  W5: { title: 'Translation & polish · Chinese ↔ English', problem: 'Slow external-facing copy', tools: 'DeepL/Claude/ChatGPT' },
  W6: { title: 'Competitive & industry quick research', problem: 'Scattered, slow research', tools: 'Perplexity/ChatGPT/Kimi' },
  W7: { title: 'Slides & presentations · Outline + speaker notes', problem: 'Hard to structure', tools: 'Gamma/ChatGPT/Beautiful.ai' },
  W8: { title: 'Email & message batch replies', problem: 'Repetitive replies', tools: 'ChatGPT/Superhuman AI' },
  W9: { title: 'Calendar & meetings · Smart scheduling summaries', problem: 'Scheduling coordination is tedious', tools: 'Reclaim/Clockwise/飞书' },
  W10: { title: 'Contract & long-document summary (you final-review)', problem: "Can't read it all", tools: 'Claude/ChatGPT' },
  W11: { title: 'Excel & spreadsheets · Formula generation & cleanup', problem: 'Stuck on spreadsheets', tools: 'Excel Copilot/ChatGPT Code' },
  W12: { title: 'Interview & hiring · JD & question lists', problem: 'Slow to write job descriptions', tools: 'ChatGPT/Claude' },
  W13: { title: 'Cross-team project sync material consolidation', problem: 'Slow to stitch multi-party info', tools: 'Claude/ChatGPT' },
  W14: { title: 'SOP & process document library generation', problem: 'Missing process documentation', tools: 'Claude/Notion AI' },
  W15: { title: 'Budget & forecast model notes + narrative', problem: 'Hard to communicate finance', tools: 'ChatGPT+Excel' },

  D1: { title: 'Coding · You set standards → Agent writes', problem: 'Boilerplate code is slow', tools: 'Cursor Agent/Claude Code/Copilot' },
  D2: { title: 'Refactoring & tech debt', problem: 'Afraid to refactor', tools: 'Cursor/Claude Code' },
  D3: { title: 'Unit & integration test generation', problem: 'Insufficient coverage', tools: 'Cursor/Copilot/Codex' },
  D4: { title: 'Code review first pass', problem: 'Review bottleneck', tools: 'Cursor/Claude/Coderabbit' },
  D5: { title: 'Docs & API sync generation', problem: 'Outdated documentation', tools: 'Cursor/Swag AI' },
  D6: { title: 'Debugging · Logs → hypotheses → patch', problem: 'Ocean of logs', tools: 'Cursor/ChatGPT/Claude' },
  D7: { title: 'CI & build failure interpretation', problem: "Can't read the red text", tools: 'Cursor/Copilot' },
  D8: { title: 'Dependency & security upgrade analysis', problem: 'Afraid to upgrade', tools: 'Dependabot+AI/Cursor' },
  D9: { title: 'Architecture design · Option comparison (you choose)', problem: "Can't think of all options", tools: 'Claude/ChatGPT/o1' },
  D10: { title: 'SQL / regex / one-off script generation', problem: "Can't remember syntax", tools: 'Cursor/Codex/ChatGPT' },
  D11: { title: 'Migration & data scripts', problem: 'Afraid of migration errors', tools: 'Claude Code/Cursor' },
  D12: { title: 'Terminal & ops command assistance', problem: "Can't remember commands", tools: 'Warp AI/Fig/Cursor' },
  D13: { title: 'Full integration of unfamiliar SDK/API', problem: 'Slow to read docs and integrate', tools: 'Cursor/CC/Codex' },
  D14: { title: 'App Store listing materials & review responses', problem: 'Publishing busywork', tools: 'ChatGPT/Cursor' },
  D15: { title: 'Data pipeline ETL script generation', problem: 'Slow pipeline setup', tools: 'Claude Code/Cursor' },

  B1: { title: 'Internal knowledge Q&A RAG', problem: 'Repeated HR/IT answers', tools: 'Dify/Coze/飞书知识库' },
  B2: { title: 'External customer FAQ + human handoff', problem: 'Customer support pressure', tools: 'Dify/Intercom AI/Zendesk AI' },
  B3: { title: 'Sales scripts / proposals / bids', problem: 'Slow proposals', tools: 'ChatGPT/Claude/Jasper' },
  B4: { title: 'Ticket auto-classification & routing', problem: 'Manual ticket triage', tools: 'Zapier AI/n8n/custom' },
  B5: { title: 'Approval & contract summaries', problem: "Long docs unread", tools: 'Claude/ChatGPT' },
  B6: { title: 'In-product AI features', problem: 'Competitive pressure', tools: 'OpenAI API/custom Agent' },
  B7: { title: 'Marketing copy / SEO / ad creatives', problem: 'Slow output', tools: 'ChatGPT/Midjourney/Jasper' },
  B8: { title: 'User feedback & review sentiment analysis', problem: "Can't read all feedback", tools: 'ChatGPT/MonkeyLearn' },
  B9: { title: 'User interviews → insight report (heavy)', problem: 'Interview synthesis takes days', tools: 'Claude/ChatGPT/Dovetail AI' },
  B10: { title: 'Quarterly OKR & roadmap planning', problem: 'Alignment takes too long', tools: 'Claude/ChatGPT/Notion AI' },
  B11: { title: 'Pricing & monetization strategy analysis', problem: 'Scattered decision info', tools: 'Claude/o1/Perplexity' },
  B12: { title: 'Churn / retention analysis & win-back plans', problem: 'Slow data analysis + strategy', tools: 'ChatGPT+BI/Julius' },

  X1: { title: 'Understand legacy codebase / new hire onboarding', problem: 'Days lost on inherited projects', tools: 'Cursor/CC + codebase chat' },
  X2: { title: 'Deep industry & market research report', problem: '1–3 days of research', tools: 'Perplexity Deep/o1/Claude' },
  X3: { title: 'Full resume + portfolio + job search strategy overhaul', problem: 'Job change prep takes days', tools: 'Claude/ChatGPT' },
  X4: { title: 'Annual finance review / tax prep organization', problem: 'Full day organizing accounts', tools: 'ChatGPT+Excel/CPA final review' },
  X5: { title: 'Multi-month project plan + WBS + risk register', problem: 'Half-day+ on large project planning', tools: 'Claude/ChatGPT/Notion AI' },
  X6: { title: 'Fundraising / board / investor deck', problem: '1–2 days preparing materials', tools: 'Claude/Gamma/ChatGPT' },
  X7: { title: 'Compliance & regulatory long-document review summary', problem: "Legal text unread", tools: 'Claude 200K/ChatGPT' },
  X8: { title: 'Multi-source user research synthesis → insight report', problem: 'Days synthesizing interviews + surveys', tools: 'Claude/Dovetail/ChatGPT' },
  X9: { title: 'Full training course / handbook system build', problem: 'Week+ to build a course', tools: 'ChatGPT/NotebookLM' },
  X10: { title: 'Incident postmortem + improvement tracking', problem: 'Slow to write postmortem reports', tools: 'Claude/ChatGPT' },
  X11: { title: 'Agent-autonomous multi-file feature (hours to days)', problem: 'Long cross-module dev cycles', tools: 'Cursor Agent/CC/Devin' },
  X12: { title: 'Full-module E2E / regression test suite generation', problem: 'Days to backfill tests', tools: 'Cursor/Copilot/Codex' },
  X13: { title: 'Security audit / vulnerability triage + fix plan', problem: 'Days for security assessment', tools: 'Cursor+Snyk+AI' },
  X14: { title: 'Full-repo migration / data migration plan + scripts', problem: 'Slow migration planning + execution', tools: 'Claude Code/Cursor' },
  X15: { title: 'Quarterly product roadmap + release planning', problem: 'Full day on planning alignment', tools: 'Claude/ChatGPT' },
  X16: { title: 'Full GTM / product launch plan', problem: 'Days of launch planning', tools: 'Claude/ChatGPT/Jasper' },
  X17: { title: 'Contract / agreement first draft (lawyer final review)', problem: 'Slow to write contracts from scratch', tools: 'Claude/ChatGPT' },
  X18: { title: 'RFP drafting + vendor evaluation matrix', problem: 'Days in procurement process', tools: 'Claude/ChatGPT' },
  X19: { title: '360 performance reviews / promotion materials', problem: 'Painful review season', tools: 'Claude/ChatGPT' },
  X20: { title: 'Major life planning (move / wedding / renovation / study abroad)', problem: 'Days coordinating complex affairs', tools: 'ChatGPT/Claude/Kimi' },
  X21: { title: 'Competitive feature matrix + differentiation strategy (deep)', problem: '1+ day competitive analysis', tools: 'Perplexity/Claude/ChatGPT' },
  X22: { title: 'Full-repo doc generation / update (synced with code)', problem: 'Documentation debt accumulates', tools: 'Cursor/Swag AI' },
  X23: { title: 'Performance profiling report + optimization plan', problem: 'Hours to days on performance investigation', tools: 'Cursor/ChatGPT+APM' },
  X24: { title: 'Microservices split / architecture evolution plan', problem: 'Days on architecture design', tools: 'Claude/o1/CC' },
  X25: { title: 'Medical / checkup report organization + question list (not diagnosis)', problem: "Reports hard to understand", tools: 'ChatGPT/Claude' },

  R1: { title: 'Manual research → Deep Research + you verify', problem: 'Research compressed from 2 days to 2h', tools: 'Perplexity/o1/Claude' },
  R2: { title: 'Manual data entry → OCR/screenshot + AI extraction + you confirm', problem: 'Hours of data entry', tools: 'GPT-4V/通义/飞书 OCR' },
  R3: { title: 'Pure human support → RAG Q&A + human fallback', problem: '80% of questions are repeats', tools: 'Dify/Coze/Intercom' },
  R4: { title: 'Manual QA → AI exploratory testing + human sign-off', problem: "Can't finish regression", tools: 'Cursor/Mobile AI/Playwright+AI' },
  R5: { title: 'Verbal onboarding → AI-guided + knowledge base', problem: 'New hires ask the same questions', tools: 'RAG+Notion/飞书' },
  R6: { title: 'Manual weekly reports → data pull + AI narrative', problem: '2h/week assembling data', tools: 'n8n+ChatGPT/BI Copilot' },
  R7: { title: 'Manual troubleshooting → log aggregation + AI hypothesis ranking', problem: 'Long MTTR', tools: 'Datadog+AI/Cursor' },
  R8: { title: 'Manual meeting notes → recording auto-pipeline summary', problem: 'Post-meeting pain every time', tools: '飞书妙记/Plaud+AI' },
  R9: { title: 'Optional code review → AI mandatory first pass on all PRs', problem: 'Review queue backlog', tools: 'Coderabbit/Cursor/Claude' },
  R10: { title: 'Backfill tests → spec-driven AI generation + CI gate', problem: 'Test debt', tools: 'Cursor/Copilot' },
  R11: { title: 'Manual competitive monitoring → scheduled agent scrape + push', problem: 'Stale intelligence', tools: 'n8n/Coze/Perplexity API' },
  R12: { title: 'Manual i18n → extract + AI translate + human review', problem: 'Localization takes weeks', tools: 'Lokalise+AI/Cursor' },
  R13: { title: 'Manual Excel → NL queries + fixed template automation', problem: 'Spreadsheet drudgery', tools: 'Excel Copilot/Python+AI' },
  R14: { title: 'Read full approval docs → summary + risk flags + you approve', problem: 'Approval backlog', tools: 'Claude/ChatGPT' },
  R15: { title: 'Manual resume screening → AI structured matching + you interview', problem: 'Slow HR first pass', tools: 'ChatGPT/ATS AI' },
  R16: { title: 'Ad-hoc content → AI content calendar + you publish', problem: 'Content gaps in ops', tools: 'ChatGPT/Coze' },
  R17: { title: 'Ad-hoc analysis → text-to-SQL + fixed dashboards', problem: 'Re-fetch data every time', tools: 'Julius/Metabase AI' },
  R18: { title: 'Manual deploy → agent scripts + you approve', problem: 'Many deployment steps', tools: 'Claude Code/Cursor/CI' },
  R19: { title: 'Rotting docs → code-change-triggered AI doc sync', problem: 'Docs always outdated', tools: 'Cursor/Swag/hooks' },
  R20: { title: 'Grind new courses → dump materials in NotebookLM + review plan', problem: 'Learning without structure', tools: 'NotebookLM/ChatGPT' },
  R21: { title: 'Manual social replies → AI draft inbox + you approve', problem: "Can't keep up with comments", tools: 'Coze/ChatGPT' },
  R22: { title: 'Meeting overload → multi-meeting merged digest + decisions', problem: 'Too many meetings', tools: 'AI+Calendar/飞书' },
  R23: { title: 'Repetitive browser actions → Computer Use Agent', problem: 'Clicking the same pages', tools: 'Operator/Claude CU/Manus' },
  R24: { title: 'Spec-driven dev → PRD → Task → Agent loop', problem: 'Long requirements-to-code chain', tools: 'Cursor/CC+TaskMaster' },
  R25: { title: 'Personal inbox zero → AI email/message triage + drafts', problem: 'Message pile-up', tools: 'Superhuman/Shortwave AI' },

  N1: { title: 'Final business / strategy / major life decisions', problem: 'AI does not bear consequences', tools: 'AI may only list options + trade-offs', aiRole: 'Prepare options; you decide' },
  N2: { title: 'External legal signing / final legal opinion', problem: 'Legal liability rests with humans', tools: 'AI may only summarize risks', aiRole: 'Summary + question list; lawyer/you sign' },
  N3: { title: 'Financial finalization / audit sign-off / tax filing signature', problem: 'Compliance and number accuracy', tools: 'AI may only organize & categorize', aiRole: 'Organize accounts; you/CPA confirm' },
  N4: { title: 'Medical diagnosis / medication / treatment decisions', problem: 'Regulation and safety', tools: 'AI cannot replace a doctor', aiRole: 'Organize reports + question list' },
  N5: { title: 'Termination / discipline / sensitive HR decisions', problem: 'Humanity + legal risk', tools: 'AI may only draft framework', aiRole: 'Process checklist; you/HR conduct meeting' },
  N6: { title: 'Crisis PR / final external messaging on public opinion', problem: 'Reputation is irreversible', tools: 'AI may only draft', aiRole: 'Multiple draft versions; you finalize & publish' },
  N7: { title: 'Intimate relationships / trust / emotional repair', problem: 'Requires a real person present', tools: 'AI may only suggest wording', aiRole: 'Draft for reference; real conversation required' },
  N8: { title: 'Parenting / education values & key conversations', problem: 'Parent role is irreplaceable', tools: 'AI may only prepare materials', aiRole: 'Materials + talking points; you deliver' },
  N9: { title: 'Final creative aesthetic / brand tone approval', problem: 'Personal / brand expression', tools: 'AI may only produce drafts', aiRole: 'Multiple versions; you pick direction' },
  N10: { title: 'Exam hall / certification cheating via ghostwriting', problem: 'Integrity and rules', tools: 'AI ghostwriting prohibited', aiRole: 'Study aid only outside exams' },
  N11: { title: 'Physical construction / surgery / hazardous field work', problem: 'Personal safety', tools: 'AI cannot operate in physical world', aiRole: 'Look up standards; human executes' },
  N12: { title: 'Sensitive data entered into AI without redaction', problem: 'Leakage and compliance risk', tools: 'Prohibited', aiRole: 'Redact first or use enterprise tier' },
  N13: { title: 'Final merge of payment / auth / security-critical code', problem: 'Hallucination = incident', tools: 'AI review + human final approval', aiRole: 'AI first pass; you merge' },
  N14: { title: 'Final moral / ethical / values judgment', problem: 'AI has no value stance', tools: 'AI may only provide framework', aiRole: 'Ethics matrix; you judge' },
  N15: { title: 'Final negotiation concessions / floor price / deal close', problem: 'Relationship + strategy', tools: 'AI may only simulate', aiRole: 'Role-play prep; you at the table' },
  N16: { title: 'Investment / large capital final order placement', problem: 'P&L responsibility is personal', tools: 'AI may only research', aiRole: 'Research summary; you decide' },
  N17: { title: 'Privacy policy / user consent legal commitments', problem: 'Legal liability', tools: 'AI may only draft', aiRole: 'Legal + your final review' },
  N18: { title: 'Whether to disclose security incidents / disclosure content', problem: 'Compliance + reputation', tools: 'AI may only build timeline', aiRole: 'Fact organization; you decide' },
  N19: { title: 'Team trust / morale / critical 1-on-1s', problem: 'Management requires human touch', tools: 'AI may only provide talking outline', aiRole: 'Outline for reference; real conversation' },
  N20: { title: 'In-person contract signing / witnessing / physical delivery', problem: 'Physical + legal requirements', tools: 'Remote AI signing not allowed', aiRole: 'AI assists electronic docs; human signs' },
  N21: { title: 'Final performance ratings / promotion veto', problem: 'Affects others\' careers', tools: 'AI may only organize evidence', aiRole: 'Material prep; manager decides' },
  N22: { title: 'Final product launch / shutdown go-no-go', problem: 'Business consequences', tools: 'AI may only provide checklist', aiRole: 'Risk list; PM/you decide' },
  N23: { title: 'Press interviews / public speaking off-script commitments', problem: 'One sentence cannot be taken back', tools: 'AI may only prepare script', aiRole: 'Q&A prep; you own the room' },
  N24: { title: 'Decisions involving minors / vulnerable groups', problem: 'Protection and compliance', tools: 'Restrict AI use', aiRole: 'Extreme caution; multi-person review' },
  N25: { title: 'Formal filings & responses to regulators / government', problem: 'Legal consequences', tools: 'AI may only draft', aiRole: 'Professional advisor + you submit' },

  A1: { title: 'Cursor Agent · Multi-file autonomous coding', problem: 'Cross-file tasks are slow', tools: 'Cursor Pro/Business' },
  A2: { title: 'Claude Code (CC) · Terminal coding agent', problem: 'CLI workflow', tools: 'Claude Pro/Max' },
  A3: { title: 'OpenAI Codex / Codex CLI', problem: 'Cloud sandbox execution', tools: 'ChatGPT Pro/Codex' },
  A4: { title: 'GitHub Copilot · Agent / Coding Agent', problem: 'GitHub ecosystem', tools: 'Copilot Pro+' },
  A5: { title: 'Windsurf Cascade Agent', problem: 'In-IDE agent', tools: 'Windsurf Pro' },
  A6: { title: 'Cline / Roo Code · VS Code agent', problem: 'Open-source configurable models', tools: 'VS Code+Cline' },
  A7: { title: 'Aider · Git-aware terminal pair', problem: 'Terminal preference', tools: 'Aider+API' },
  A8: { title: 'Devin / similar fully autonomous engineer', problem: 'Long-task autonomy', tools: 'Devin/Cognition' },
  A9: { title: 'Bolt.new / Lovable · Full-stack generation', problem: 'Zero to MVP', tools: 'Bolt/Lovable' },
  A10: { title: 'Replit Agent · Cloud build & deploy', problem: 'Rapid prototyping', tools: 'Replit Core' },
  A11: { title: 'OpenHands / SWE-Agent open source', problem: 'Self-hosted agent', tools: 'Docker+GPU' },
  A12: { title: 'v0 · UI component generation', problem: 'Slow frontend UI', tools: 'Vercel v0' },
  A13: { title: 'Manus / general-purpose task agent', problem: 'Long-task autonomy', tools: 'Manus' },
  A14: { title: 'OpenAI Operator · Computer Use', problem: 'Browser automation', tools: 'ChatGPT Pro' },
  A15: { title: 'Claude Computer Use', problem: 'GUI operation agent', tools: 'Claude' },
  A16: { title: 'Multi-hour agent · Multi-hour tasks', problem: 'Long multi-step tasks', tools: 'CC/Cursor/Devin' },
  A17: { title: 'TaskMaster / Spec → Task breakdown', problem: 'Breaking large requirements into tasks', tools: 'TaskMaster AI' },
  A18: { title: 'OpenClaw (Lobster) · self-hosted personal AI assistant', problem: 'Multi-IM channels, always-on local, plugin ecosystem', tools: 'OpenClaw + API' },
  A19: { title: 'Hermes Agent (Hermès) · self-improving agent', problem: 'Cross-session memory, self-learned skills, scheduled jobs', tools: 'Hermes + API/VPS' },
  A20: { title: 'Flowith · canvas agent workflows', problem: 'Multi-model orchestration, visual agent chains', tools: 'Flowith' },

  T1: { title: 'ChatGPT · GPT-4o/o1/Pro', problem: 'General chat + reasoning', tools: 'OpenAI' },
  T2: { title: 'Claude · Sonnet/Opus', problem: 'Long docs + writing + code', tools: 'Anthropic' },
  T3: { title: 'Gemini · Advanced/Workspace', problem: 'Google ecosystem', tools: 'Google' },
  T4: { title: 'DeepSeek · Reasoning/code', problem: 'Cost-effective coding', tools: 'DeepSeek' },
  T5: { title: 'Kimi · Long context', problem: 'Long documents', tools: '月之暗面' },
  T6: { title: '通义千问 · DingTalk/Alibaba Cloud', problem: 'Domestic compliance', tools: '阿里' },
  T7: { title: '文心一言 · Baidu ecosystem', problem: 'Domestic search', tools: '百度' },
  T8: { title: '豆包 · ByteDance suite', problem: 'Free + mobile-first', tools: '字节' },
  T9: { title: 'Perplexity · Search + citations', problem: 'Research needing sources', tools: 'Perplexity' },
  T10: { title: 'NotebookLM · Doc podcast / RAG', problem: 'Make materials queryable', tools: 'Google' },
  T11: { title: 'Grok · X/Twitter integration', problem: 'Social real-time', tools: 'xAI' },
  T12: { title: 'Enterprise tier · Data not used for training', problem: 'Work compliance', tools: 'Team/Enterprise' },

  F1: { title: 'Coze / 扣子 · Bot + plugins', problem: 'Fast bot setup in China', tools: '字节 Coze' },
  F2: { title: 'Dify · RAG + Agent open source', problem: 'Private RAG deployment', tools: 'Dify' },
  F3: { title: 'n8n / Make · AI workflows', problem: 'Cross-app automation', tools: 'n8n/Make' },
  F4: { title: 'Zapier AI Actions', problem: 'SaaS wiring', tools: 'Zapier' },
  F5: { title: 'Apple Shortcuts + AI', problem: 'Phone automation', tools: 'Shortcuts' },
  F6: { title: 'Raycast AI / Alfred AI', problem: 'Mac launcher AI', tools: 'Raycast' },
  F7: { title: 'Notion AI / 飞书智能', problem: 'In-document AI', tools: 'Notion/飞书' },
  F8: { title: 'Obsidian Copilot plugin', problem: 'Local notes RAG', tools: 'Obsidian' },

  M1: { title: 'Midjourney / DALL·E / SD', problem: 'Image generation', tools: 'MJ/DALL-E' },
  M2: { title: 'Suno / Udio · AI music', problem: 'Soundtracks', tools: 'Suno' },
  M3: { title: 'Runway / Kling / Sora', problem: 'Video generation', tools: 'Runway/Kling' },
  M4: { title: 'ElevenLabs · Voice synthesis', problem: 'Voiceover', tools: 'ElevenLabs' },
  M5: { title: 'Descript / 剪映 AI', problem: 'Editing', tools: 'Descript/剪映' },
  M6: { title: 'Canva AI / 稿定 AI', problem: 'Design templates', tools: 'Canva' },

  H1: { title: 'AI PC · NPU (Copilot+ PC)', problem: 'Local inference / privacy', tools: 'Intel/AMD/Qualcomm X Elite' },
  H2: { title: 'Apple Silicon Mac · M-series', problem: 'Local small models + development', tools: 'MacBook/Mac mini' },
  H3: { title: 'Local GPU workstation · Ollama', problem: 'Private large models', tools: 'NVIDIA RTX + Ollama' },
  H4: { title: 'Plaud Note / recording card', problem: 'Meeting / idea recording → AI', tools: 'Plaud' },
  H5: { title: 'Apple Intelligence · iPhone/Mac', problem: 'System-level summary / writing', tools: 'iOS 18+/macOS' },
  H6: { title: 'Smart glasses · Meta Ray-Ban etc.', problem: 'First-person capture', tools: 'Meta/雷鸟' },
  H7: { title: 'AI mouse/keyboard · Quick wake', problem: 'Physical one-key AI', tools: 'Various' },
  H8: { title: 'Smart speakers · Voice assistants', problem: 'Home voice control', tools: '小爱/天猫/HomePod' },
  H9: { title: 'Apple Watch / health AI interpretation', problem: 'Understanding health data', tools: 'Apple Watch' },
  H10: { title: 'VR/AR · Vision Pro spatial computing', problem: 'Immersive collaboration', tools: 'Vision Pro' },

  K1: { title: 'Cursor / Claude Skills · install & daily use', problem: 'Repeat work not captured; re-explaining context each time', tools: 'Cursor Skills / Claude Code' },
  K2: { title: 'Author custom Skill (SKILL.md) for SOPs', problem: 'Similar tasks not one-click reusable', tools: 'Cursor / Claude Skill author' },
  K3: { title: 'Pick from skill collections · team shared library', problem: 'Unaware of existing skills', tools: 'skills.sh / GitHub collections' },
  K4: { title: 'MCP tool integration · Agent calls external capabilities', problem: 'Agent lacks DB/browser/API access', tools: 'MCP server ecosystem' },
  K5: { title: 'Prompt templates as skills (notes / weekly / PRD)', problem: 'Good prompts lost after one use', tools: 'prompts/ + Skills' },
  K6: { title: 'Multi-skill orchestration · end-to-end workflow', problem: 'Point skills do not form a system', tools: 'CC / Cursor Agent + Skills' },
  K7: { title: 'Hot agent rollout · Lobster / Hermès / IM channels', problem: 'Installed trendy agents but no IM hookup or skills', tools: 'OpenClaw / Hermes / Feishu·Telegram' },

  I1: { title: 'E-commerce · Product copy / detail pages / support scripts', problem: 'Many SKUs; slow output', tools: 'ChatGPT/Jasper/店小秘 AI' },
  I2: { title: 'Education · Lesson plans / exercises / homework feedback', problem: 'Prep and grading take time', tools: 'ChatGPT/Claude/讯飞' },
  I3: { title: 'Law firm · Case search / document drafts (lawyer final review)', problem: 'Slow search and drafting', tools: 'Claude/ChatGPT/法律 AI' },
  I4: { title: 'Medical documentation · Chart organization / discharge summaries (not diagnosis)', problem: 'Heavy documentation burden', tools: 'Claude/specialty AI · human review' },
  I5: { title: 'Manufacturing · SOP / QC reports / equipment maintenance logs', problem: 'Field docs lag behind', tools: 'ChatGPT+MES/Notion AI' },
  I6: { title: 'Finance · Compliance summaries / research / risk briefs', problem: 'Information-dense; unread', tools: 'Claude/ChatGPT/Bloomberg AI' },

  Q1: { title: 'Data classification · what can go to cloud vs local-only', problem: 'Sensitive data uploaded to cloud models', tools: 'Written tiers: public/internal/confidential/local-only + tool mapping' },
  Q2: { title: 'Personal vs work account separation', problem: 'Work data in personal ChatGPT', tools: 'Team/Enterprise · dedicated work account · no mixing' },
  Q3: { title: 'Top 10 frequent scenarios in written SOPs', problem: 'Ad-hoc use only; no trigger', tools: 'Document: when, which tool, where output goes' },
  Q4: { title: 'Top 5 packaged as Skill / Prompt templates', problem: 'Re-explaining context every time', tools: 'Skill library / prompts/ · one-click invoke' },
  Q5: { title: '100% human review on external output', problem: 'Hallucinations sent as-is', tools: 'Email/contract/posts/merge · fixed final reviewer' },
  Q6: { title: 'Sensitive work on local / private AI', problem: 'Source/customer/finance on public cloud', tools: 'Ollama/LM Studio/enterprise · redact first' },
  Q7: { title: 'Model routing and cost caps', problem: 'Always using most expensive models', tools: 'Cheap draft / strong finalize · monthly budget · routing table' },
  Q8: { title: 'Agent fallback paths', problem: 'Lobster/Hermès/cloud down = blocked', tools: 'Backup tool · manual SOP · degradation list' },
  Q9: { title: 'Project context pack kept in sync', problem: 'AI lacks background on new projects', tools: 'CLAUDE.md / Cursor Rules / AGENTS.md' },
  Q10: { title: 'Monthly snapshot + cut unused subs', problem: 'Subscription creep; unclear ROI', tools: 'Save snapshot here · monthly sub review' },
  Q11: { title: 'Monthly mis-delegation audit', problem: 'No review of what should stay human', tools: 'Human pool · misDelegation flags · monthly review' },
  Q12: { title: 'Team Skill shared library (team) / personal library (solo)', problem: 'Good skills stuck in personal chats', tools: 'Shared Git/Notion · solo: personal Skill repo' },
};
